import type { ProgramInfo, WorkingGroup } from './types';

export const PROGRAM: ProgramInfo = {
  name: 'Программа проектов цифровизации',
  period: '2025–2027',
  sponsor: 'Директор по цифровой трансформации',
};

export const INITIAL_GROUPS: WorkingGroup[] = [
  {
    id: 'rg-arch',
    name: 'Рабочая группа «Архитектура и интеграции»',
    shortName: 'Архитектура',
    leaderId: 'm-ivanov',
    members: [
      {
        id: 'm-ivanov',
        name: 'Иванов А.С.',
        role: 'Руководитель РГ, главный архитектор',
        responsibilities: [
          'Целевая ИТ-архитектура программы',
          'Согласование интеграционных решений',
          'Контроль соответствия проектов стандартам',
        ],
      },
      {
        id: 'm-petrova',
        name: 'Петрова Е.В.',
        role: 'Ведущий системный аналитик',
        responsibilities: [
          'Описание сквозных бизнес-процессов',
          'Матрица интеграций между системами',
        ],
      },
      {
        id: 'm-sidorov',
        name: 'Сидоров К.М.',
        role: 'Архитектор интеграций',
        responsibilities: [
          'Проектирование API и шин данных',
          'Техническая экспертиза change-запросов',
        ],
      },
    ],
    assignments: [
      {
        id: 'a-1',
        title: 'Актуализировать целевую архитектуру v2.3',
        source: 'schedule',
        ownerId: 'm-ivanov',
        dueDate: '2025-06-15',
        status: 'in_progress',
        scheduleRef: 'ПГ-2.1',
      },
      {
        id: 'a-2',
        title: 'Согласовать интеграцию CRM ↔ ERP',
        source: 'tracker',
        ownerId: 'm-sidorov',
        dueDate: '2025-06-10',
        status: 'review',
      },
      {
        id: 'a-3',
        title: 'Подготовить реестр интерфейсов',
        source: 'schedule',
        ownerId: 'm-petrova',
        dueDate: '2025-05-28',
        status: 'overdue',
        scheduleRef: 'ПГ-2.4',
      },
    ],
    documents: [
      {
        id: 'd-1',
        code: 'АРХ-01',
        title: 'Целевая ИТ-архитектура программы',
        ownerId: 'm-ivanov',
        dueDate: '2025-06-20',
        status: 'in_progress',
      },
      {
        id: 'd-2',
        code: 'АРХ-02',
        title: 'Матрица интеграций',
        ownerId: 'm-petrova',
        dueDate: '2025-06-05',
        status: 'review',
      },
      {
        id: 'd-3',
        code: 'АРХ-03',
        title: 'Стандарты API и обмена данными',
        ownerId: 'm-sidorov',
        dueDate: '2025-07-01',
        status: 'draft',
      },
    ],
  },
  {
    id: 'rg-data',
    name: 'Рабочая группа «Данные и аналитика»',
    shortName: 'Данные',
    leaderId: 'm-kozlov',
    members: [
      {
        id: 'm-kozlov',
        name: 'Козлов Д.И.',
        role: 'Руководитель РГ, директор по данным',
        responsibilities: [
          'Стратегия управления данными',
          'Качество и мастер-данные',
          'Витрины аналитики программы',
        ],
      },
      {
        id: 'm-novikova',
        name: 'Новикова О.П.',
        role: 'Дата-инженер',
        responsibilities: [
          'ETL-пайплайны и DWH',
          'Каталог данных',
        ],
      },
      {
        id: 'm-fedorov',
        name: 'Фёдоров Р.А.',
        role: 'BI-аналитик',
        responsibilities: [
          'Дашборды KPI программы',
          'Отчётность для руководства',
        ],
      },
    ],
    assignments: [
      {
        id: 'a-4',
        title: 'Запустить пилот MDM по контрагентам',
        source: 'schedule',
        ownerId: 'm-kozlov',
        dueDate: '2025-06-30',
        status: 'in_progress',
        scheduleRef: 'ПГ-3.2',
      },
      {
        id: 'a-5',
        title: 'Настроить витрину KPI цифровизации',
        source: 'tracker',
        ownerId: 'm-fedorov',
        dueDate: '2025-06-18',
        status: 'in_progress',
      },
      {
        id: 'a-6',
        title: 'Миграция исторических данных в DWH',
        source: 'schedule',
        ownerId: 'm-novikova',
        dueDate: '2025-05-20',
        status: 'done',
        scheduleRef: 'ПГ-3.1',
      },
    ],
    documents: [
      {
        id: 'd-4',
        code: 'ДАН-01',
        title: 'Политика управления данными',
        ownerId: 'm-kozlov',
        dueDate: '2025-06-25',
        status: 'review',
      },
      {
        id: 'd-5',
        code: 'ДАН-02',
        title: 'Каталог данных программы',
        ownerId: 'm-novikova',
        dueDate: '2025-07-10',
        status: 'in_progress',
      },
      {
        id: 'd-6',
        code: 'ДАН-03',
        title: 'Спецификация витрин KPI',
        ownerId: 'm-fedorov',
        dueDate: '2025-06-12',
        status: 'approved',
      },
    ],
  },
  {
    id: 'rg-change',
    name: 'Рабочая группа «Процессы и Change Management»',
    shortName: 'Change',
    leaderId: 'm-volkova',
    members: [
      {
        id: 'm-volkova',
        name: 'Волкова Н.Г.',
        role: 'Руководитель РГ, менеджер изменений',
        responsibilities: [
          'План управления изменениями',
          'Обучение и вовлечение пользователей',
          'Коммуникации программы',
        ],
      },
      {
        id: 'm-morozov',
        name: 'Морозов П.Л.',
        role: 'Бизнес-аналитик',
        responsibilities: [
          'Описание to-be процессов',
          'GAP-анализ as-is / to-be',
        ],
      },
    ],
    assignments: [
      {
        id: 'a-7',
        title: 'Провести сессию вовлечения ключевых стейкхолдеров',
        source: 'tracker',
        ownerId: 'm-volkova',
        dueDate: '2025-06-08',
        status: 'done',
      },
      {
        id: 'a-8',
        title: 'Подготовить план обучения волна 1',
        source: 'schedule',
        ownerId: 'm-volkova',
        dueDate: '2025-06-22',
        status: 'not_started',
        scheduleRef: 'ПГ-4.3',
      },
      {
        id: 'a-9',
        title: 'Завершить GAP-анализ по HR-процессам',
        source: 'schedule',
        ownerId: 'm-morozov',
        dueDate: '2025-06-14',
        status: 'in_progress',
        scheduleRef: 'ПГ-4.1',
      },
    ],
    documents: [
      {
        id: 'd-7',
        code: 'CHG-01',
        title: 'План управления изменениями',
        ownerId: 'm-volkova',
        dueDate: '2025-06-30',
        status: 'in_progress',
      },
      {
        id: 'd-8',
        code: 'CHG-02',
        title: 'Матрица заинтересованных сторон',
        ownerId: 'm-volkova',
        dueDate: '2025-05-30',
        status: 'approved',
      },
      {
        id: 'd-9',
        code: 'CHG-03',
        title: 'Описание to-be процессов (волна 1)',
        ownerId: 'm-morozov',
        dueDate: '2025-06-16',
        status: 'review',
      },
    ],
  },
  {
    id: 'rg-infra',
    name: 'Рабочая группа «Инфраструктура и безопасность»',
    shortName: 'Инфра',
    leaderId: 'm-belov',
    members: [
      {
        id: 'm-belov',
        name: 'Белов С.В.',
        role: 'Руководитель РГ, CISO',
        responsibilities: [
          'Информационная безопасность программы',
          'Политики доступа и аудит',
        ],
      },
      {
        id: 'm-orlova',
        name: 'Орлова М.К.',
        role: 'Инженер облачной инфраструктуры',
        responsibilities: [
          'Облачные стенды и CI/CD',
          'Мониторинг и отказоустойчивость',
        ],
      },
    ],
    assignments: [
      {
        id: 'a-10',
        title: 'Провести аудит ИБ перед go-live пилота',
        source: 'schedule',
        ownerId: 'm-belov',
        dueDate: '2025-06-05',
        status: 'overdue',
        scheduleRef: 'ПГ-5.2',
      },
      {
        id: 'a-11',
        title: 'Развернуть staging-контур для интеграций',
        source: 'tracker',
        ownerId: 'm-orlova',
        dueDate: '2025-06-12',
        status: 'in_progress',
      },
    ],
    documents: [
      {
        id: 'd-10',
        code: 'ИБ-01',
        title: 'Модель угроз и меры защиты',
        ownerId: 'm-belov',
        dueDate: '2025-06-10',
        status: 'overdue',
      },
      {
        id: 'd-11',
        code: 'ИНФ-01',
        title: 'Архитектура облачной инфраструктуры',
        ownerId: 'm-orlova',
        dueDate: '2025-06-28',
        status: 'in_progress',
      },
    ],
  },
  {
    id: 'rg-pmo',
    name: 'Рабочая группа «Управление программой»',
    shortName: 'PMO',
    leaderId: 'm-lebedev',
    members: [
      {
        id: 'm-lebedev',
        name: 'Лебедев В.Н.',
        role: 'Руководитель программы (PMO)',
        responsibilities: [
          'План-график программы и контроль вех',
          'Эскалации и отчётность SteerCo',
          'Координация рабочих групп',
        ],
      },
      {
        id: 'm-sokolova',
        name: 'Соколова И.А.',
        role: 'Координатор проектов',
        responsibilities: [
          'Ведение реестра поручений',
          'Подготовка статус-отчётов',
        ],
      },
    ],
    assignments: [
      {
        id: 'a-12',
        title: 'Актуализировать план-график Q2',
        source: 'schedule',
        ownerId: 'm-lebedev',
        dueDate: '2025-06-03',
        status: 'done',
        scheduleRef: 'ПГ-1.1',
      },
      {
        id: 'a-13',
        title: 'Подготовить материалы SteerCo 12.06',
        source: 'tracker',
        ownerId: 'm-sokolova',
        dueDate: '2025-06-11',
        status: 'in_progress',
      },
    ],
    documents: [
      {
        id: 'd-12',
        code: 'ПГ-01',
        title: 'План-график программы (базовый)',
        ownerId: 'm-lebedev',
        dueDate: '2025-06-01',
        status: 'approved',
      },
      {
        id: 'd-13',
        code: 'ПГ-02',
        title: 'Еженедельный статус-отчёт программы',
        ownerId: 'm-sokolova',
        dueDate: '2025-06-09',
        status: 'in_progress',
      },
      {
        id: 'd-14',
        code: 'ПГ-03',
        title: 'Реестр рисков программы',
        ownerId: 'm-lebedev',
        dueDate: '2025-06-20',
        status: 'draft',
      },
    ],
  },
];
